#!/usr/bin/env python3
"""Build and verify mock i18n bundles (ch14 §14.11.4)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = REPO_ROOT / "docs" / "mockups" / "shared" / "locales"
JA_JSON = LOCALES_DIR / "ja.json"
EN_JSON = LOCALES_DIR / "en.json"
BUNDLE_OUT = LOCALES_DIR / "ja.bundle.js"

EN_OVERRIDES: dict[str, str] = {
    "_meta.lang_name": "English",
    "error.e_nightly_008.warn": "Parameter change exceeds ±10% (warning)",
    "error.e_nightly_008.error": "Apply blocked: parameter change exceeds ±20%",
    "warning.large_change": "Change exceeds ±10% (warning)",
    "error.reject_large_change": "Apply blocked: change exceeds ±20%",
    "page.emergency_stop.title": "Emergency Stop",
    "page.emergency_stop.subtitle": "Review stop state and recovery",
    "health.degraded": "System health degraded",
}


def load_json(path: Path) -> dict[str, str]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"Expected object in {path}")
    return {str(k): str(v) for k, v in raw.items()}


def key_to_en(key: str) -> str:
    if key in EN_OVERRIDES:
        return EN_OVERRIDES[key]
    if key.startswith("_meta."):
        return key
    tail = key.split(".")[-1]
    return tail.replace("_", " ").replace(".", " ").title()


def ensure_en_keys(ja: dict[str, str], en: dict[str, str]) -> dict[str, str]:
    merged = dict(en)
    for key, ja_val in ja.items():
        if key not in merged:
            merged[key] = key_to_en(key) if key not in EN_OVERRIDES else EN_OVERRIDES[key]
        elif key in EN_OVERRIDES:
            merged[key] = EN_OVERRIDES[key]
    return merged


def write_bundle(ja: dict[str, str], en: dict[str, str]) -> None:
    ja_lines = [f'  "{k}": {json.dumps(v, ensure_ascii=False)},' for k, v in sorted(ja.items())]
    en_lines = [f'  "{k}": {json.dumps(v, ensure_ascii=False)},' for k, v in sorted(en.items())]
    body = (
        "/* Auto-generated by tools/build_locales.py — do not edit by hand */\n"
        "(function (g) {\n"
        '  "use strict";\n'
        "  g.YORUU_LOCALES = g.YORUU_LOCALES || {};\n"
        "  g.YORUU_LOCALES.ja = {\n"
        + "\n".join(ja_lines)
        + "\n};\n"
        "  g.YORUU_LOCALES.en = {\n"
        + "\n".join(en_lines)
        + "\n};\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )
    BUNDLE_OUT.write_text(body, encoding="utf-8")


def cmd_check() -> int:
    ja = load_json(JA_JSON)
    en = load_json(EN_JSON)
    ja_keys = set(ja)
    en_keys = set(en)
    only_ja = sorted(ja_keys - en_keys)
    only_en = sorted(en_keys - ja_keys)
    if only_ja or only_en:
        if only_ja:
            print("Keys missing in en.json:", file=sys.stderr)
            for key in only_ja:
                print(f"  + {key}", file=sys.stderr)
        if only_en:
            print("Keys missing in ja.json:", file=sys.stderr)
            for key in only_en:
                print(f"  - {key}", file=sys.stderr)
        return 1
    print(f"OK: {len(ja_keys)} keys match between ja.json and en.json")
    return 0


def cmd_build() -> int:
    ja = load_json(JA_JSON)
    en_existing = load_json(EN_JSON) if EN_JSON.is_file() else {}
    en = ensure_en_keys(ja, en_existing)
    EN_JSON.write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_bundle(ja, en)
    print(f"Wrote {EN_JSON.name} and {BUNDLE_OUT.name} ({len(ja)} keys)")
    return cmd_check()


def extract_bundle_keys(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    return set(re.findall(r'"([^"]+)"\s*:', text))


def main() -> int:
    parser = argparse.ArgumentParser(description="YoRuu mock locale tooling")
    parser.add_argument("--check", action="store_true", help="Verify ja/en key parity")
    parser.add_argument("--build", action="store_true", help="Sync en.json and regenerate ja.bundle.js")
    args = parser.parse_args()
    if args.build:
        return cmd_build()
    if args.check:
        return cmd_check()
    parser.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
