#!/usr/bin/env python3
"""Build and verify mock i18n bundles (ch14 §14.11.4)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCALES_DIR = REPO_ROOT / "docs" / "mockups" / "shared" / "locales"
JA_JSON = LOCALES_DIR / "ja.json"
EN_JSON = LOCALES_DIR / "en.json"
BUNDLE_OUT = LOCALES_DIR / "ja.bundle.js"

EN_OVERRIDES: dict[str, str] = {
    "_meta.lang_name": "English",
    "error.e_nightly_008.warn": "Parameter change exceeds ±10% (warning)",
    "error.e_nightly_008.error": "Apply blocked: parameter change exceeds ±20%",
    "warning.large_change": "Change exceeds ±10% (warning)",
    "error.reject_large_change": "Apply blocked: change exceeds ±20%",
    "page.emergency_stop.title": "Emergency Stop",
    "page.emergency_stop.subtitle": "Review stop state and recovery",
    "health.degraded": "System health degraded",
}

def load_json(path: Path) -> dict[str, str]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"Expected object in {path}")
    return {str(k): str(v) for k, v in raw.items()}


def key_to_en(key: str) -> str:
    if key in EN_OVERRIDES:
        return EN_OVERRIDES[key]
    if key.startswith("_meta."):
        return key
    tail = key.split(".")[-1]
    return tail.replace("_", " ").replace(".", " ").title()


def ensure_en_keys(ja: dict[str, str], en: dict[str, str]) -> dict[str, str]:
    merged = dict(en)
    for key, ja_val in ja.items():
        if key not in merged:
            merged[key] = key_to_en(key) if key not in EN_OVERRIDES else EN_OVERRIDES[key]
        elif key in EN_OVERRIDES:
            merged[key] = EN_OVERRIDES[key]
    return merged


def write_bundle(ja: dict[str, str], en: dict[str, str]) -> None:
    ja_lines = [f'  "{k}": {json.dumps(v, ensure_ascii=False)},' for k, v in sorted(ja.items())]
    en_lines = [f'  "{k}": {json.dumps(v, ensure_ascii=False)},' for k, v in sorted(en.items())]
    body = (
        "/* Auto-generated by tools/build_locales.py — do not edit by hand */\n"
        "(function (g) {\n"
        '  "use strict";\n'
        "  g.YORUU_LOCALES = g.YORUU_LOCALES || {};\n"
        "  g.YORUU_LOCALES.ja = {\n"
        + "\n".join(ja_lines)
        + "\n};\n"
        "  g.YORUU_LOCALES.en = {\n"
        + "\n".join(en_lines)
        + "\n};\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )
    BUNDLE_OUT.write_text(body, encoding="utf-8")


# Leftover values from key_to_en() before M4.8 hand translation.
SUSPECT_EN_VALUES: frozenset[str] = frozenset(
    {
        "Title",
        "Subtitle",
        "Label",
        "Short",
        "Upper",
        "Desc",
        "Preview",
        "Goto Hud",
        "Go Hud",
        "Link Hub",
        "Link Dashboard",
        "Usd",
        "Jpy",
        "Stale",
        "Placeholder",
        "Cumulative Pnl",
        "Total Assets",
        "Max Win",
        "Avg Size",
        "Recent Trades",
        "Goto Dashboard",
        "Goto Trade Log",
        "Goto Nightly Review",
        "Goto Settings",
        "Goto Strategy History",
        "Goto Markov Live",
        "Goto What If",
        "Goto Alerts",
        "Goto Mode Switch",
        "Goto Hub",
        "Export Csv",
        "Export Json",
        "Apply Filter",
        "Prev Page",
        "Next Page",
        "Unread Count",
        "Palette Placeholder",
        "Shortcuts Title",
        "Cmd K",
        "Main Nav",
        "Modal Label",
        "Current Page",
        "Scenario Select",
        "Last Trade",
        "Paste Label",
        "Prompt Section",
        "Report Date",
        "Trades Total",
        "Win Rate",
        "Paste Area",
        "Parse Ok",
        "Parse Fail",
        "Copy All",
        "Copy All Done",
        "Diff Check",
        "Missing Key",
        "Out Of Range",
        "Parse Failed",
        "Apply Title",
        "Apply Body",
        "Apply Ok",
        "Rollback Title",
        "Rollback Body",
        "Version Card",
        "Applied At",
        "Matrix Title",
        "From To",
        "Persistence Chart",
        "Edge Panel",
        "Min Prob Panel",
        "Window N",
        "Threshold Line",
        "Entry Ok",
        "Insufficient Data",
        "Apply Done",
        "Rollback Done",
        "Strategy Readonly",
        "Yaml Editor",
        "Link Strategy",
        "Restart Required",
        "Unread Only",
        "Mark Read",
        "Mark All Read",
        "Switch To",
        "Live Step1 Title",
        "Live Step1 Body",
        "Live Step1 Placeholder",
        "Live Step2 Title",
        "Live Step2 Body",
        "Live Final Ok",
        "Live Check Ws",
        "Live Check Balance",
        "Live Check Loss Limit",
        "Live Check Emergency",
        "Mode Simple",
        "Live Text Mismatch",
        "Mode Switch Idle Only",
        "Emergency No Live",
        "Emergency No Live Body",
        "Mode Demo Idle",
        "Mode Switched",
        "Triggered At",
        "Trigger Source",
        "State Snapshot",
        "Logs Download",
        "Recovered",
        "Whatif Recalc",
        "Whatif Saved",
    }
)


def find_placeholder_en(ja: dict[str, str], en: dict[str, str]) -> list[str]:
    """Keys whose en value matches known auto-generated placeholders."""
    suspects: list[str] = []
    for key in sorted(ja):
        if key.startswith("_meta."):
            continue
        val = en.get(key, "")
        if not val or val in SUSPECT_EN_VALUES:
            suspects.append(key)
    return suspects


def cmd_check() -> int:
    ja = load_json(JA_JSON)
    en = load_json(EN_JSON)
    ja_keys = set(ja)
    en_keys = set(en)
    only_ja = sorted(ja_keys - en_keys)
    only_en = sorted(en_keys - ja_keys)
    if only_ja or only_en:
        if only_ja:
            print("Keys missing in en.json:", file=sys.stderr)
            for key in only_ja:
                print(f"  + {key}", file=sys.stderr)
        if only_en:
            print("Keys missing in ja.json:", file=sys.stderr)
            for key in only_en:
                print(f"  - {key}", file=sys.stderr)
        return 1
    placeholders = find_placeholder_en(ja, en)
    if placeholders:
        print("Placeholder EN strings (fix en.json):", file=sys.stderr)
        for key in placeholders:
            print(f"  {key}: {en[key]!r}", file=sys.stderr)
        return 1
    print(f"OK: {len(ja_keys)} keys match between ja.json and en.json")
    return 0


def cmd_build() -> int:
    ja = load_json(JA_JSON)
    en_existing = load_json(EN_JSON) if EN_JSON.is_file() else {}
    en = ensure_en_keys(ja, en_existing)
    EN_JSON.write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_bundle(ja, en)
    print(f"Wrote {EN_JSON.name} and {BUNDLE_OUT.name} ({len(ja)} keys)")
    return cmd_check()


def extract_bundle_keys(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    return set(re.findall(r'"([^"]+)"\s*:', text))


def main() -> int:
    parser = argparse.ArgumentParser(description="YoRuu mock locale tooling")
    parser.add_argument("--check", action="store_true", help="Verify ja/en key parity")
    parser.add_argument("--build", action="store_true", help="Sync en.json and regenerate ja.bundle.js")
    args = parser.parse_args()
    if args.build:
        return cmd_build()
    if args.check:
        return cmd_check()
    parser.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
